"""JackVerse Caseworker: Governed Case Management Layer.

"Give it a goal or a problem. JackVerse manages the case."
"""

from caseworker.domain import (
    AccessDecision,
    Action,
    ActionStatus,
    ActionType,
    Approval,
    ApprovalStatus,
    ApprovalValidationError,
    Case,
    CaseStatus,
    CaseType,
    CaseworkerError,
    Claim,
    ClaimStatus,
    ClaimVerificationPolicy,
    CompletenessResult,
    ContextAccessPolicy,
    ContextFact,
    ContextPackage,
    ContextPackageBuilder,
    ContextSource,
    DomainEvent,
    DomainValidationError,
    EntityNotFoundError,
    InvalidStateTransitionError,
    Mission,
    MissionKind,
    MissionStatus,
    Opportunity,
    OpportunityStatus,
    OpportunityType,
    OptimisticLockError,
    PersistenceError,
    ProfileCompletenessEvaluator,
    ProfileRequirement,
    RequirementSet,
    RiskLevel,
    SensitivityLevel,
    SourceType,
    VerificationStatus,
)
from caseworker.persistence import (
    ActionRepository,
    ApprovalRepository,
    CaseRepository,
    CaseworkerUnitOfWork,
    ClaimRepository,
    ContextRepository,
    ContextSourceRepository,
    EventStore,
    MissionRepository,
    OpportunityRepository,
    SQLiteActionRepository,
    SQLiteApprovalRepository,
    SQLiteCaseRepository,
    SQLiteCaseworkerStorage,
    SQLiteCaseworkerUnitOfWork,
    SQLiteClaimRepository,
    SQLiteContextRepository,
    SQLiteContextSourceRepository,
    SQLiteEventStore,
    SQLiteMigrator,
    SQLiteMissionRepository,
    SQLiteOpportunityRepository,
)
from caseworker.services import (
    CaseService,
    ClaimLedgerService,
    ContextVaultService,
    MissionService,
)

__version__ = "0.2.0"

__all__ = [
    # Domain entities & aggregates
    "Mission",
    "Case",
    "Opportunity",
    "Action",
    "Approval",
    "ContextSource",
    "ContextFact",
    "Claim",
    "ContextPackage",
    "DomainEvent",
    # Enums
    "MissionStatus",
    "MissionKind",
    "CaseStatus",
    "CaseType",
    "OpportunityType",
    "OpportunityStatus",
    "ActionType",
    "ActionStatus",
    "RiskLevel",
    "ApprovalStatus",
    "SourceType",
    "VerificationStatus",
    "SensitivityLevel",
    "ClaimStatus",
    # Policies & Evaluators
    "ContextAccessPolicy",
    "AccessDecision",
    "ClaimVerificationPolicy",
    "ContextPackageBuilder",
    "ProfileRequirement",
    "RequirementSet",
    "CompletenessResult",
    "ProfileCompletenessEvaluator",
    # Errors
    "CaseworkerError",
    "EntityNotFoundError",
    "InvalidStateTransitionError",
    "OptimisticLockError",
    "DomainValidationError",
    "ApprovalValidationError",
    "PersistenceError",
    # Persistence Protocols
    "MissionRepository",
    "CaseRepository",
    "OpportunityRepository",
    "ActionRepository",
    "ApprovalRepository",
    "ContextSourceRepository",
    "ContextRepository",
    "ClaimRepository",
    "EventStore",
    "CaseworkerUnitOfWork",
    # Migration & Storage
    "SQLiteMigrator",
    "SQLiteCaseworkerStorage",
    "SQLiteCaseworkerUnitOfWork",
    "SQLiteMissionRepository",
    "SQLiteCaseRepository",
    "SQLiteOpportunityRepository",
    "SQLiteActionRepository",
    "SQLiteApprovalRepository",
    "SQLiteContextSourceRepository",
    "SQLiteContextRepository",
    "SQLiteClaimRepository",
    "SQLiteEventStore",
    # Services
    "MissionService",
    "CaseService",
    "ContextVaultService",
    "ClaimLedgerService",
]

